---
# tasks file for worker
- name: substring token to var
  local_action: "shell tail -n 2 /home/centos/kubernetes-ansible/token.log"
  register: add_node_command

- name: add k8s noden
  shell: "{{add_node_command.stdout}} --ignore-preflight-errors=all"
