---
# tasks file for kubeconfig
- name: create kube directory
  file:
    path: $HOME/.kube
    mode: u=rwX,g=rX,o=rX
    state: directory
    recurse: yes
    force: yes
  become: no

- name: copy admin.conf file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{hostvars['k8s'].ansible_user}}/.kube/config
    remote_src: yes
    owner: "{{hostvars['k8s'].ansible_user}}"
    group: "{{hostvars['k8s'].ansible_user}}"
  become: yes
