---
# handlers file for common

- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: Restart docker service
  service:
    name: docker
    enabled: yes
    state: restarted
  become: yes
