- name: download heapster by git
  git: 
    repo: https://github.com/kubernetes-retired/heapster.git
    dest: /home/{{hostvars['k8s'].ansible_user}}/heapster

- name: install heapster
  command: "{{item}}"
  with_items:  
  - kubectl create -f /home/{{hostvars['k8s'].ansible_user}}/heapster/deploy/kube-config/influxdb/
  - kubectl create -f /home/{{hostvars['k8s'].ansible_user}}/heapster/deploy/kube-config/rbac/heapster-rbac.yaml
  environment:
    KUBECONFIG: /home/{{hostvars['k8s'].ansible_user}}/.kube/config

