- name: install docker required packages
  apt:
    name: "{{ item }}"
  with_items:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  become: yes

- name: Create Folder fo GPG key 
  file:
    path: /etc/apt/keyrings
    state: directory
  become: yes
  
- name: remove docker gpg
  command: rm -rf /etc/apt/keyrings/docker.gpg
  become: yes

- name: remove docker repo
  command: rm -rf /etc/apt/sources.list.d/docker.list
  become: yes

- name: Add Docker’s official GPG key URL
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  become: yes

- name: Add Docker’s official Repo
  shell:  "echo \
          \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
  become: yes

- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"
  become: yes

- name: update docker repo
  apt:
    name: '*'
    state: latest
  become: yes

- name: install specific docker's version
  apt: 
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  with_items:
    - docker-ce=5:{{ docker_version }}~3-0~ubuntu-focal
    - docker-ce-cli=5:{{ docker_version }}~3-0~ubuntu-focal
    - containerd.io
    - docker-compose-plugin
  notify: Restart docker service
  become: yes


- name: call flush handlers
  meta: flush_handlers


- name: mkdir docker directory
  file: 
    path: /etc/docker
    state: directory
    mode: u=rwX,g=rX,o=rX
  become: yes

- name: Set cgroup by systemd
  shell:
    cmd: |
      cat <<EOF > /etc/docker/daemon.json
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF
  become: yes


- name: mkdir docker service directory
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
    recurse: yes
  become: yes

- name: add docker group
  group: 
    name: docker
    state: present
  become: yes

- name: docker group mod
  shell: sudo usermod -aG docker {{ ansible_env.USER }}  
  become: yes