---
# - hosts: no-master
#   roles:
#   - { role: ubuntu/uninstall-docker}
#   - { role: ubuntu/docker}
# - hosts: no-master
#   roles:
#   - { role: ubuntu/common}
- hosts: all
  roles:
  - { role: common}
  - { role: cri-o}
  - { role: install-kube}
  - { role: podman}
  - { role: reset} 
- hosts: master
  roles:
  - { role: master}
- hosts: ha-master
  roles:
  - { role: ha-master}
- hosts: all-master
  roles:
  - { role: kubeconfig}
- hosts: worker
  roles:
  - { role: worker}
- hosts: master
  roles:
  - { role: cni/calico}