---
# - hosts: no-master
#   roles:
#   - { role: ubuntu/uninstall-docker}
#   - { role: ubuntu/docker}
# - hosts: no-master
#   roles:
#   - { role: ubuntu/common}
- hosts: worker
  roles:
  # - { role: istio-config}
  - { role: common}
  - { role: cri-o}
  - { role: install-kube}
  - { role: podman}
  - { role: reset} 
# - hosts: master
#   roles:
#   - { role: master}
#   - { role: cni/calico}
# - hosts: ha-master
#   roles:
#   - { role: ha-master}
- hosts: worker
  roles:
  - { role: worker}
# - hosts: all-master
#   roles:
#   - { role: kubeconfig}
- hosts: all
  roles:
  - { role: crio-restart}
  