---
- name: create kubernetes repo
  shell:
    cmd: |
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
      EOF
  become: yes

- name: update kubernetes repo
  yum: 
    name: '*'
    state: latest
    nobest: true
  become: yes

- name: unlock kubelet kubeadm kubectl version lock
  community.general.yum_versionlock:
    state: absent
    name: "{{ item }}"
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: install kubelet kubeadm kubectl
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - kubelet-{{ kube_version }}
    - kubeadm-{{ kube_version }}
    - kubectl-{{ kube_version }}
  become: yes

- name: kubelet start
  service:
    name: kubelet
    enabled: yes
    state: restarted
  become: yes

- name: lock kubeadm, kubelet, kubectl version
  community.general.yum_versionlock:
    state: present
    name: "{{ item }}"
  with_items:
    - kubelet-{{ kube_version }}
    - kubeadm-{{ kube_version }}
    - kubectl-{{ kube_version }}
  become: yes

- name: echo k8s bash completion to bashrc
  shell: echo 'source <(kubectl completion bash)' >> /home/{{ ansible_env.USER }}/.bashrc