- name: Taint all master node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  become: yes
  environment: 
    KUBECONFIG: /home/{{hostvars['k8s'].ansible_user}}/.kube/config

- name: Set master node label
  apt: 
    name: "{{ item }}"
    state: absent
  with_items:
    - kubectl label nodes {{ all_node_name[0] }} node= {{ all_node_k8s_label[0] }}
    - kubectl label nodes {{ all_node_name[1] }} node= {{ all_node_k8s_label[1] }}
    - kubectl label nodes {{ all_node_name[2] }} node= {{ all_node_k8s_label[2] }}
    - kubectl label nodes {{ all_node_name[3] }} node= {{ all_node_k8s_label[3] }}
  environment: 
    KUBECONFIG: /home/{{hostvars['k8s'].ansible_user}}/.kube/config
  become: yes